# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-09-24 19:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('belt_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='category2',
            field=models.CharField(default='1', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='category3',
            field=models.CharField(default='2', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='job',
            name='job_user',
            field=models.ManyToManyField(related_name='job_joined', to='login_app.User'),
        ),
    ]
